**SCATTER PLOTS**

In [1]:
# Plottng
import matplotlib.pyplot as plt

# Data manipulation
import numpy as np

# Machine learning
from sklearn import datasets


*Resources:*

matplotlib.pyplot.scatter

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html

Scatter Plot Example

https://matplotlib.org/stable/gallery/shapes_and_collections/scatter.html



**PAIRS OF FEATURES**

In [2]:
# https://scikit-learn.org/stable/datasets/toy_dataset.html
diabetes = datasets.load_diabetes()

# Show
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [3]:
# https://scikit-learn.org/stable/datasets/toy_dataset.html
diabetes = datasets.load_diabetes()

# Show
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [4]:
# https://scikit-learn.org/stable/datasets/toy_dataset.html
diabetes = datasets.load_diabetes()

# Show
diabetes.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [5]:
# Data
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [8]:
# Blood pressure
bp = diabetes.data[:, 3] # The same as: [0:len(data), 3] The column at index 3 (the fourth column)

# Show
bp

array([ 2.18723855e-02, -2.63275281e-02, -5.67042229e-03, -3.66560811e-02,
        2.18723855e-02, -1.94418262e-02, -1.59989752e-02,  6.66294482e-02,
       -4.00989321e-02, -3.32132301e-02,  8.10098161e-03, -3.32132301e-02,
       -9.11327327e-03,  8.10098161e-03, -1.25561242e-02,  8.04008521e-02,
        4.94151933e-02,  5.63008953e-02, -3.66560811e-02, -4.00989321e-02,
       -4.35417830e-02,  1.21527966e-03, -9.11327327e-03,  3.10647976e-02,
       -2.28846772e-02, -4.00989321e-02, -2.63275281e-02, -4.00989321e-02,
       -7.45274418e-02,  6.31865972e-02, -1.94418262e-02, -8.14131438e-02,
        2.87580875e-02, -2.22757132e-03, -5.73131869e-02, -4.92913442e-02,
        5.28580443e-02, -5.73131869e-02,  9.76151070e-02, -7.45274418e-02,
        2.18723855e-02, -1.08955952e-01, -1.48628344e-02, -7.10845908e-02,
        8.10098161e-03,  3.22009384e-02, -3.32132301e-02, -5.73131869e-02,
        1.15438326e-02, -5.67042229e-03,  1.49866836e-02,  2.87580875e-02,
       -5.67042229e-03,  

In [ ]:
# BMI
bmi = diabetes.data[:, 2]

# Show
bmi[:10] # The first ten values

array([ 0.06169621, -0.05147406,  0.04445121, -0.01159501, -0.03638469,
       -0.04069594, -0.04716281, -0.00189471,  0.06169621,  0.03906215])