In [19]:
# Numerical arrays
import numpy as np

**Multidimensional Homogeneous Arrays**

In [20]:
a = np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [21]:
# A 2D array of integers.
X = np.array([[1,2,3], [4,5,6]])

# Show
print(X)

[[1 2 3]
 [4 5 6]]


In [22]:
# 2D Array ( a list of lists)

[
    [1,2,3,4],   # rectangular array
    [5,6,7,8]
]

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [23]:
[
    [1,2,3,4],
    [5,6,7,8],
    [8,9,0]
]

[[1, 2, 3, 4], [5, 6, 7, 8], [8, 9, 0]]

In [24]:
# A 3D array of integers

T = [
    [
        [1,2],[3,4],[5,6]
    ],
    [
        [7,8],[9,0],[1,2]
    ],
    [
        [3,4],[5,6],[7,8]
    ] 
]

In [11]:
T

[[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 0], [1, 2]], [[3, 4], [5, 6], [7, 8]]]

In [25]:
T[0]

[[1, 2], [3, 4], [5, 6]]

In [26]:
T[0][0]

[1, 2]

In [27]:
T[0][0][0]  # 3 different indices so it's 3-dimensional (3D)

1

In [28]:
[
    [1,2.0],  # Heterogeneous array (data structure) as there are 2 different data types
    [3,4]
]

[[1, 2.0], [3, 4]]

In [29]:
[
    ['a','b'],
    ['c','d']
]

[['a', 'b'], ['c', 'd']]

In [30]:
# Number of dimensions
print(X.ndim)

2


In [31]:
# Shape of the array
print(X.shape)

(2, 3)


There are 2 rows and 3 columns (that's the shape)

In [32]:
# Type of the elements
print(X.dtype)

int64


**OPERATIONS**

In [33]:
# Two arrays
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

# Show
print('A:')
print(A)
print('B:')
print(B)


A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [34]:
# Adding constants.
A + 5

array([[6, 7],
       [8, 9]])

In [35]:
# Adding two arrays
A + B

array([[ 6,  8],
       [10, 12]])

In [36]:
# Multiplying by a constant.
A * 2

array([[2, 4],
       [6, 8]])

In [37]:
# Multiplying two arrays.
A * B

array([[ 5, 12],
       [21, 32]])

In [38]:
# Matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

**ACCESSING ELEMENTS**

In [39]:
A

array([[1, 2],
       [3, 4]])

In [40]:
A[0]

array([1, 2])

In [ ]:
A[0][1] # Row 0 column 1

np.int64(2)

In [43]:
A[0,1] # The same as A[0][1]

np.int64(2)

In [45]:
A[1,0] # Row 1 column 0

np.int64(3)

In [ ]:
A[:,0] # Everything in column 0 (every row)

array([1, 3])

In [48]:
# Zeroth row, first column 
a[0,1]

np.int64(2)

In [49]:
# Zeroth row
A[0]

array([1, 2])

In [50]:
# First column
A[:,1]

array([2, 4])

In [55]:
# An array with lots of elements
X = np.arange(10, 20)

# Show
print(X)

[10 11 12 13 14 15 16 17 18 19]


In [56]:
# An array with lots of elements
X = np.arange(20)

# Show
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# An array with lots of elements
X = np.arange(10, 21, 3) # (starting point, finishing (ending) point, the step)

# Show
print(X)

[10 13 16 19]


In [67]:
# An array with lots of elements
X = np.arange(20)

# Show
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# The first five elements
X[:5] # Up to but not including index 5

array([0, 1, 2, 3, 4])

In [69]:
# The next five elements
X[5:10]

array([5, 6, 7, 8, 9])

In [70]:
# Every second element
X[0:len(X):2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
# The elements from index 5 up
X[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [74]:
# Every second element # he same as X[0:len(X):2]
X[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])